swagger: "2.0"
info:
  description: "A idéia baseia-se na construção de um dispositivo Arduino que auxiliará as pessoas com deficiências auditivas a treinarem a fala através de simulação das vibrações das palavras que são feitas pelas cordas vocais do ser humano."
  version: "1.0.0"
  title: "TDVE - Teaching-Directed Vibration Emitter"
  termsOfService: "http://??????.??/terms/"
  contact:
    email: "tdve@hotmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "tdve.swagger.io"
basePath: "/v2"
tags:
  
- name: "Vocabulario"
  description: "Base de palavras ou frases que serao aprendidas pelos alunos"
  
schemes:
- "https"
- "http"
paths:
  /Vocabulario:
    post:
      tags:
      - "Vocabulario"
      summary: "Adicionar uma nova palavra a base de palavras"
      description: ""
      operationId: "addPalavra"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Palavra precisa ser adicionada a base do Banco de Dados"
        required: true
        schema:
          $ref: "#/definitions/Vocabulario"
      responses:
        "405":
          description: "Invalid input"
      security:
      - tdvemachine_auth:
        - "write:vocabulario"
        - "read:vocabulario"
    put:
      tags:
      - "Vocabulario"
      summary: "Atualizar uma palavra"
      description: ""
      operationId: "AlterarPalavra"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Nova palavra precisa ser adicionada a base"
        required: true
        schema:
          $ref: "#/definitions/Vocabulario"
      responses:
        "405":
          description: "Validation exception"
      security:
      - tdvemachine_auth:
        - "write:vocabulario"
        - "read:vocabulario"
  /Vocabulario/{palavraId}:
    get:
      tags:
      - "Vocabulario"
      summary: "Encontrar palavra pelo ID"
      description: "Retornar uma unica palavra"
      operationId: "getWordById"
      produces:
      - "application/json"
      parameters:
      - name: "palavraId"
        in: "path"
        description: "ID da palavra retorna"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Vocabulario"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Palavra não encontrada"
      security:
      - api_key: []
    post:
      tags:
      - "Vocabulario"
      summary: "Atualizar / Adicionar palavra em um formulario"
      description: ""
      operationId: "updateWordWithForm"
      consumes:
      - "application/x-www-form-urlencoded"
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
      - name: "palavraId"
        in: "path"
        description: "ID da palavra precisa ser atualizado"
        required: true
        type: "integer"
        format: "int64"
      - name: "desc_palavra"
        in: "formData"
        description: "Atualiza escrita da palavra"
        required: false
        type: "string"
      - name: "binario_palavra"
        in: "formData"
        description: "Atualizar código binário da palavra"
        required: false
        type: "file"
      responses:
        "405":
          description: "Invalid input"
      security:
      - tdvemachine_auth:
        - "write:vocabulario"
        - "read:vocabulario"
    delete:
      tags:
      - "Vocabulario"
      summary: "Deletar uma palavra"
      description: ""
      operationId: "deletarPalavra"
      produces:
      - "application/json"
      parameters:
      - name: "api_key"
        in: "header"
        required: false
        type: "string"
      - name: "palavraId"
        in: "path"
        description: "Palavra a ser deletada"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Palavra não encontrada"
      security:
      - tdvemachine_auth:
        - "write:vocabulario"
        - "read:vocabulario"

securityDefinitions:
  tdvemachine_auth:
    type: "oauth2"
    authorizationUrl: "http://tdve.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:vocabulario: "insere sugestoes de palavras novas na aplicacao"
      read:vocabulario: "le as palavras requeridas"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
    
definitions:
  Vocabulario:
    type: "object"
    properties:
      palavraId:
        type: "string"
      desc_palavra:
        type: "string"
      binario_palavra:
        type: "object"
      complete:
        type: "boolean"
        default: false
    xml:
      name: "Vocabulario"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
