swagger: "2.0"
info:
  description: "A idéia baseia-se na construção de um dispositivo Arduino que auxiliará as pessoas com deficiências auditivas a treinarem a fala através de simulação das vibrações das palavras que são feitas pelas cordas vocais do ser humano."
  version: "1.0.0"
  title: "TDVE - Teaching-Directed Vibration Emitter"
  termsOfService: "http://??????.??/terms/"
  contact:
    email: "tdve@hotmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "tdve.swagger.io"
basePath: "/v2"
tags:

- name: "User"
  description: "Base de usuários da aplicação. Será utilizada para controle de acesso a informação"
  
- name: "Vocabulario"
  description: "Base de palavras ou frases que serao aprendidas pelos alunos"
  
- name: "Log"
  description: "Logs da aplicação"
  
- name: "PalavraAprendida"
  description: "Palavras aprendidas apendidas pela aplicação"
  
- name: "Ranking"
  description: "Ranking dos usuários da aplicação"
  
schemes:
- "https"
- "http"
paths:
  /User:
    get:
      tags: 
      - "User"
      summary: "Consulta lista de usuários"
      description: ""
      operationId: "getUsers"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "Lista de usuários da aplicação"
        "403":
          description: "Acesso Negado"
    post:
      tags:
      - "User"
      summary: "Adicionar um novo usuário"
      operationId: "postUser"
      parameters:
      - in: "body"
        name: "body"
        description: "Usuário a ser cadastrado"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        "200":
          description: "Usuário adicionado com sucesso"
        "403":
          description: "Acesso Negado"
  /User/{id}:
    get:
      tags: 
      - "User"
      summary: "Consulta um usuário especifico"
      description: ""
      operationId: "getUser"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "ID do usuário a ser consultado"
        required: true
        type: "string"
        format: "string"
      responses:
        "200":
          description: "Objeto do usuário procurado"
        "403":
          description: "Acesso Negado"
    put:
      tags:
      - "User"
      summary: "Adicionar um novo usuário"
      operationId: "putUser"
      parameters:
      - name: "id"
        in: "path"
        description: "ID do usuário a ser atualizado"
        required: true
        type: "string"
        format: "string"
      - in: "body"
        name: "body"
        description: "Usuário a ser cadastrado"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        "200":
          description: "Usuário atualizado com sucesso"
        "403":
          description: "Acesso Negado"
    patch:
      tags:
      - "User"
      summary: "Adicionar um novo usuário"
      operationId: "patchUser"
      parameters:
      - name: "id"
        in: "path"
        description: "ID do usuário a ser atualizado"
        required: true
        type: "string"
        format: "string"
      - in: "body"
        name: "body"
        description: "Usuário a ser cadastrado"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        "200":
          description: "Usuário atualizado com sucesso"
        "403":
          description: "Acesso Negado"
    delete:
      tags:
      - "User"
      summary: "Deletar um usuário"
      operationId: "deleteUser"
      parameters:
      - name: "id"
        in: "path"
        description: "ID do usuário a ser deletado"
        required: true
        type: "string"
        format: "string"
      responses:
        "200":
          description: "Usuário deletado com sucesso"
        "403":
          description: "Acesso Negado"
  /Log:
    get:
      tags:
      - "Log"
      summary: "Consulta de logs"
      operationId: "getLogs"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "Lista de logs"
        "403":
          description: "Acesso Negado"
    post:
      tags:
      - "Log"
      summary: "Registro de log"
      operationId: "postLog"
      consumes:
      - "applicaion/json"
      produces:
      - "application/json"
      parameters:
      - in: body
        name: "body"
        description: ""
        required: true
        schema:
          $ref: "#/definitions/Log"
      responses:
        "200":
          description: "Log salvo com sucesso"
        "403":
          description: "Acesso Negado"
      
  /Vocabulario:
    post:
      tags:
      - "Vocabulario"
      summary: "Adicionar uma nova palavra a base de palavras"
      description: ""
      operationId: "addPalavra"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Palavra precisa ser adicionada a base do Banco de Dados"
        required: true
        schema:
          $ref: "#/definitions/Vocabulario"
      responses:
        "405":
          description: "Invalid input"
      security:
      - tdvemachine_auth:
        - "write:vocabulario"
        - "read:vocabulario"
    put:
      tags:
      - "Vocabulario"
      summary: "Atualizar uma palavra"
      description: ""
      operationId: "AlterarPalavra"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Nova palavra precisa ser adicionada a base"
        required: true
        schema:
          $ref: "#/definitions/Vocabulario"
      responses:
        "405":
          description: "Validation exception"
      security:
      - tdvemachine_auth:
        - "write:vocabulario"
        - "read:vocabulario"
  /Vocabulario/{palavraId}:
    get:
      tags:
      - "Vocabulario"
      summary: "Encontrar palavra pelo ID"
      description: "Retornar uma unica palavra"
      operationId: "getWordById"
      produces:
      - "application/json"
      parameters:
      - name: "palavraId"
        in: "path"
        description: "ID da palavra retorna"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Vocabulario"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Palavra não encontrada"
      security:
      - api_key: []
    post:
      tags:
      - "Vocabulario"
      summary: "Atualizar / Adicionar palavra em um formulario"
      description: ""
      operationId: "updateWordWithForm"
      consumes:
      - "application/x-www-form-urlencoded"
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
      - name: "palavraId"
        in: "path"
        description: "ID da palavra precisa ser atualizado"
        required: true
        type: "integer"
        format: "int64"
      - name: "desc_palavra"
        in: "formData"
        description: "Atualiza escrita da palavra"
        required: false
        type: "string"
      - name: "binario_palavra"
        in: "formData"
        description: "Atualizar código binário da palavra"
        required: false
        type: "file"
      responses:
        "405":
          description: "Invalid input"
      security:
      - tdvemachine_auth:
        - "write:vocabulario"
        - "read:vocabulario"
    delete:
      tags:
      - "Vocabulario"
      summary: "Deletar uma palavra"
      description: ""
      operationId: "deletarPalavra"
      produces:
      - "application/json"
      parameters:
      - name: "api_key"
        in: "header"
        required: false
        type: "string"
      - name: "palavraId"
        in: "path"
        description: "Palavra a ser deletada"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Palavra não encontrada"
      security:
      - tdvemachine_auth:
        - "write:vocabulario"
        - "read:vocabulario"
        
  /PalavraAprendida:
    post:
      tags:
      - "PalavraAprendida"
      summary: "Adicionar uma nova palavra a base de palavras"
      description: "Adicionar a base de dados a palavra nova aprendida"
      operationId: "addPalavraAprendida"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Palavra precisa ser adicionada na base de dados"
        required: true
        schema:
          $ref: "#/definitions/PalavraAprendida"
      responses:
        "200":
          description: "Success"
        "403":
          description: "Invalid Access"
        "405":
          description: "Invalid input"
      security:
      - tdvemachine_auth:
        - "write:PalavraAprendida"
        - "read:PalavraAprendida"
    put:
      tags:
      - "PalavraAprendida"
      summary: "Atualizar a palavra aprendida"
      description: "Atualizar a palavra aprendida"
      operationId: "AlterarPalavraAprendida"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Nova palavra precisa ser adicionada a base do usuario"
        required: true
        schema:
          $ref: "#/definitions/PalavraAprendida"
      responses:
        "200":
          description: "Success"
        "403":
          description: "Invalid Access"
        "405":
          description: "Invalid input"
      security:
      - tdvemachine_auth:
        - "write:PalavraAprendida"
        - "read:PalavraAprendida"
  /PalavraAprendida/{palavraaprendidaId}:
    get:
      tags:
      - "PalavraAprendida"
      summary: "Encontrar palavra pelo ID"
      description: "Retornar uma unica palavra"
      operationId: "getWordLearnById"
      produces:
      - "application/json"
      parameters:
      - name: "palavraaprendidaId"
        in: "path"
        description: "ID da palavra aprendida retornada"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/PalavraAprendida"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Palavra não encontrada"
      security:
      - api_key: []
      
  /Ranking:
    get:
      tags:
      - "Ranking"
      summary: "Ranking por usuario"
      description: "Apresentar Ranking do Usuário"
      operationId: "getRanking"
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Palavra não encontrada"
      security:
      - api_key: []
    post:
      tags:
      - "Ranking"
      summary: "Adicionar um novo Ranking ao perfil do usuário"
      description: "Adicionar um novo Ranking ao perfil do usuário"
      operationId: "addRanking"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Ranking do usuário"
        required: true
        schema:
          $ref: "#/definitions/Ranking"
      responses:
        "200":
          description: "Success"
        "403":
          description: "Invalid Access"
        "405":
          description: "Invalid input"
      security:
      - tdvemachine_auth:
        - "write:Ranking"
        - "read:Ranking"
    put:
      tags:
      - "Ranking"
      summary: "Atualizar o novo Ranking atribuido ao usuário"
      description: "Atualizar o novo Ranking atribuido ao usuário"
      operationId: "AtualizarRanking"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Atualizar o novo Ranking atribuido ao usuário"
        required: true
        schema:
          $ref: "#/definitions/Ranking"
      responses:
        "200":
          description: "Success"
        "403":
          description: "Invalid Access"
        "405":
          description: "Invalid input"
      security:
      - tdvemachine_auth:
        - "write:Ranking"
        - "read:Ranking"
  /Ranking/{idRanking}:      
    delete:
      tags:
      - "Ranking"
      summary: "Deletar Ranking"
      operationId: "deleteRanking"
      parameters:
      - name: "idRanking"
        in: "path"
        description: "ID do usuário"
        required: true
        type: "string"
        format: "string"
      responses:
        "200":
          description: "Success"
        "403":
          description: "Invalid Access"
        "405":
          description: "Invalid input"
      security:
      - tdvemachine_auth:
        - "write:Ranking"
        - "read:Ranking"
          
securityDefinitions:
  tdvemachine_auth:
    type: "oauth2"
    authorizationUrl: "http://tdve.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:vocabulario: "insere sugestoes de palavras novas na aplicacao"
      read:vocabulario: "le as palavras requeridas"
      write:PalavraAprendida: "Insere sugestoes de palavras novas na aplicacao"
      read:PalavraAprendida: "Consulta as palavras"
      write:Ranking: "Insere Ranking do usuário"
      read:Ranking: "Lê Ranking do usuário"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
    
definitions:
  User:
    type: "object"
    properties:
      id: 
        type: "string"
      name: 
        type:  "string"
      type: 
        type:  "string"
      active: 
        type:  "boolean"
      password: 
        type:  "string"
      gender: 
        type:  "string"
      birth: 
        type:  "string"
  Log:
    type: "object"
    properties:
      text: 
        type: "string"
      source: 
        type:  "string"
  Vocabulario:
    type: "object"
    properties:
      palavraId:
        type: "string"
      desc_palavra:
        type: "string"
      binario_palavra:
        type: "object"
      complete:
        type: "boolean"
        default: false
    xml:
      name: "Vocabulario"
  PalavraAprendida:
    type: "object"
    properties:
      PalavraAprendidaID:
        type: "integer"
      PalavraSistema:
        type: "string"
    xml:
      name: "PalavraAprendida"
  Ranking:
    type: "object"
    properties:
      Ranking:
        type: "string"
      PalavraSistema:
        type: "string"
    xml:
      name: "Ranking"
      
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
